### ISSUE TITLE
Strings unescaped during the conversion

### ISSUE THREAD

**Issue by kaqqao** [helixarch/debtap#11]
I was converting Kaspersky Endpoint Security DEB (company policy to have it installed), which creates and executes a Perl script in its `preisnt`. Perl variables (and other strings) are escaped to avoid being interpreted by Bash, but during the conversation, Debtap unescaped them, causing Bash to keel over during the installation.

Example:

Original preisnt script contained:
`my (\$logic, \$pkgmgr) = klinstall::get_work_logic(\$0, \\@ARGV);`

In the generated .INSTALL, I ended up with:
`my ($logic, $pkgmgr) = klinstall::get_work_logic($0, \@ARGV);`

**Comment by helixarch** [comment]
Did you correct the errors when prompt for editing .PKGINFO and .INSTALL?

**Comment by kaqqao** [comment]
Yeah, I did fix them manually, but I think there should be a "-r" when reading the original file. No need to interpret any backslashes ta that point, right?

**Comment by helixarch** [comment]
Each line of original .deb package install scripts is being echoed inside a loop using double quites ("),

**Comment by helixarch** [comment]
Closed by accident, so I reopened the issue

Each line of the original .deb package is echoed inside a for loop using double quotes ("), slashes and backslashes SHOULD be escaped, what do you think?

**Comment by kaqqao** [comment]
I think `-r` is still needed because it's `read` that interprets them even before `echo` gets them. I'm not that good with bash, tbh, but my small test seems to confirm it.
I ran only the following lines, with and without `-r`, where `preinst` is just a text file containing a line with backslashes:

    #!/usr/bin/env bash
    grep -iv '#!\|automatically\|added\|generated' preinst | while read -r line; do
	    echo "    $line" | sed s'/        /    /g' >> test.txt
    done

Backslashes were getting stripped without the `-r`. I based most of my assumptions on this article: http://shebang.brandonmintern.com/bourne-is-not-bash-or-read-echo-and-backslash/

**Comment by helixarch** [comment]
It's a while loop (not for loop, as I mentioned by mistake before) and yes you are right. Check the new version 2.5 and tel me if it's ok now.

**Comment by helixarch** [comment]
Closing this as solved

**Comment by kaqqao** [comment]
Sorry for now replying. It looks goodI Thanks a bunch!
