### ISSUE TITLE
Here-Document terminators broken during conversion

### ISSUE THREAD

**Issue by kaqqao** [helixarch/debtap#13]
Found one more bug while converting Kaspersky.
When copying control scripts (preinst, postinst etc), all lines are prefixed by spaces (for indentation). This is usually just fine, but breaks here-document terminators as they must not have anything before or after them in the same line.

I implemented a change (will make a pull request shortly) that keeps track of all encountered here-document terminator _candidates_ and if the line matches any of them, it is not prefixed as usual. Saying _candidfates_ as it may produce false positives, but they will not affect anything as they won't match an actual line.
I tested it pretty extensively (with complicated scripts) and it seems reliable. The implementation is probably not the best, though...

**Comment by helixarch** [comment]
Can you create a commit to see what you mean?

**Comment by kaqqao** [comment]
My original idea was to remove matched terminators from the array, hence the utility function returning an index instead of a boolean, but I eventually gave up on that...

**Comment by helixarch** [comment]
Does this commit preserves spaces prefixes where is needed? Also could you create a commit for debtap-p64, too?

**Comment by kaqqao** [comment]
Yes, it leaves the spaces as they were for everything except here-document terminators. And sure, I can easily do the same for debtap-p64. Will do it later today.
Btw, I want to try making a bit prettier to have less copy-pasted stuff.

**Comment by helixarch** [comment]
It's been over a month since your last commit... Is there any update on this?

**Comment by kaqqao** [comment]
Hey. Terribly sorry for disappearing like that on you.
Changed job, no longer have a Linux computer, and in general - life happened.

I was not successful in making my changes prettier (with less repetition). Could you perhaps take a look?
Still, ugly or not, it worked fine in my tests. I can make the same changes for p64 this weekend if you're OK with that.

**Comment by helixarch** [comment]
Yes...  I am ok with that, I am planning to release a new version soon and I need these commits. Ugly or not I don't care, as long as they work.
