### ISSUE TITLE
Failed to synchronize the pkg file

### ISSUE THREAD

**Issue by talesam** [helixarch/debtap#15]
See what happens when I try to synchronize the database:

___

[neit ~]# debtap -u
==> Synchronizing pkgfile database...
:: Updating 5 repos...
warning: download failed: http://www.las.ic.unicamp.br/pub/manjarolinux/stable/extra/x86_64/extra.files [error 404]
warning: download failed: http://www.las.ic.unicamp.br/pub/manjarolinux/stable/multilib/x86_64/multilib.files [error 404]
warning: download failed: http://www.las.ic.unicamp.br/pub/manjarolinux/stable/community/x86_64/community.files [error 404]
warning: download failed: http://www.las.ic.unicamp.br/pub/manjarolinux/stable/core/x86_64/core.files [error 404]
  infinality-bundle is up to date
warning: download failed: http://linorg.usp.br/manjaro/stable/multilib/x86_64/multilib.files [error 404]
warning: download failed: http://linorg.usp.br/manjaro/stable/core/x86_64/core.files [error 404]
warning: download failed: http://repo.manjaro.org.uk/stable/multilib/x86_64/multilib.files [error 404]
warning: download failed: http://repo.manjaro.org.uk/stable/core/x86_64/core.files [error 404]
warning: download failed: http://ftp.nluug.nl/pub/os/Linux/distr/manjaro/stable/multilib/x86_64/multilib.files [error 404]
warning: download failed: http://ftp.nluug.nl/pub/os/Linux/distr/manjaro/stable/core/x86_64/core.files [error 404]
warning: download failed: http://ftp.heanet.ie/mirrors/manjaro/stable/core/x86_64/core.files [error 404]
warning: download failed: http://ftp.heanet.ie/mirrors/manjaro/stable/multilib/x86_64/multilib.files [error 404]
warning: download failed: http://ftp.snt.utwente.nl/pub/linux/manjaro/stable/core/x86_64/core.files [error 404]
warning: download failed: http://ftp.snt.utwente.nl/pub/linux/manjaro/stable/multilib/x86_64/multilib.files [error 404]
warning: download failed: http://mirrors.serverhost.ro/manjaro/packages/stable/core/x86_64/core.files [error 404]
warning: download failed: http://mirrors.serverhost.ro/manjaro/packages/stable/multilib/x86_64/multilib.files [error 404]
warning: download failed: http://linorg.usp.br/manjaro/stable/extra/x86_64/extra.files [error 404]
warning: download failed: http://mirror.yandex.ru/mirrors/manjaro/stable/core/x86_64/core.files [error 404]
warning: download failed: http://mirror.yandex.ru/mirrors/manjaro/stable/multilib/x86_64/multilib.files [error 404]
warning: download failed: http://repo.manjaro.org.uk/stable/extra/x86_64/extra.files [error 404]
warning: download failed: http://linorg.usp.br/manjaro/stable/community/x86_64/community.files [error 404]
warning: download failed: http://ftp.nluug.nl/pub/os/Linux/distr/manjaro/stable/extra/x86_64/extra.files [error 404]
warning: download failed: http://manjaro.dcc.uchile.cl/stable/core/x86_64/core.files [error 404]
warning: download failed: http://manjaro.dcc.uchile.cl/stable/multilib/x86_64/multilib.files [error 404]
warning: download failed: http://ftp.heanet.ie/mirrors/manjaro/stable/extra/x86_64/extra.files [error 404]
warning: download failed: http://repo.manjaro.org.uk/stable/community/x86_64/community.files [error 404]
warning: download failed: http://lug.mtu.edu/manjaro/stable/multilib/x86_64/multilib.files [error 404]
warning: download failed: http://lug.mtu.edu/manjaro/stable/core/x86_64/core.files [error 404]
warning: download failed: http://ftp.snt.utwente.nl/pub/linux/manjaro/stable/extra/x86_64/extra.files [error 404]
warning: download failed: http://ftp.nluug.nl/pub/os/Linux/distr/manjaro/stable/community/x86_64/community.files [error 404]
warning: download failed: http://mirrors.serverhost.ro/manjaro/packages/stable/extra/x86_64/extra.files [error 404]
warning: download failed: http://ftp.heanet.ie/mirrors/manjaro/stable/community/x86_64/community.files [error 404]
warning: download failed: http://mirror.yandex.ru/mirrors/manjaro/stable/extra/x86_64/extra.files [error 404]
warning: download failed: http://ftp.snt.utwente.nl/pub/linux/manjaro/stable/community/x86_64/community.files [error 404]
warning: download failed: http://mirror.netcologne.de/manjaro/stable/multilib/x86_64/multilib.files [error 404]
warning: download failed: http://mirror.netcologne.de/manjaro/stable/core/x86_64/core.files [error 404]
warning: download failed: http://manjaro.dcc.uchile.cl/stable/extra/x86_64/extra.files [error 404]
warning: download failed: http://mirrors.serverhost.ro/manjaro/packages/stable/community/x86_64/community.files [error 404]
warning: download failed: http://lug.mtu.edu/manjaro/stable/extra/x86_64/extra.files [error 404]
warning: download failed: http://mirror.yandex.ru/mirrors/manjaro/stable/community/x86_64/community.files [error 404]
warning: download failed: http://mirror.netcologne.de/manjaro/stable/extra/x86_64/extra.files [error 404]
warning: download failed: http://h1860261.stratoserver.net/manjaro/stable/multilib/x86_64/multilib.files [error 404]
warning: download failed: http://h1860261.stratoserver.net/manjaro/stable/core/x86_64/core.files [error 404]
warning: download failed: http://manjaro.dcc.uchile.cl/stable/community/x86_64/community.files [error 404]
warning: download failed: http://lug.mtu.edu/manjaro/stable/community/x86_64/community.files [error 404]
warning: download failed: http://h1860261.stratoserver.net/manjaro/stable/extra/x86_64/extra.files [error 404]
warning: download failed: http://mirror.netcologne.de/manjaro/stable/community/x86_64/community.files [error 404]
warning: download failed: http://h1860261.stratoserver.net/manjaro/stable/community/x86_64/community.files [error 404]
warning: download failed: http://ftp.halifax.rwth-aachen.de/manjaro/stable/multilib/x86_64/multilib.files [error 404]
warning: download failed: http://ftp.halifax.rwth-aachen.de/manjaro/stable/core/x86_64/core.files [error 404]
warning: download failed: http://ftp.halifax.rwth-aachen.de/manjaro/stable/extra/x86_64/extra.files [error 404]
warning: download failed: http://ftp.halifax.rwth-aachen.de/manjaro/stable/community/x86_64/community.files [error 404]
warning: download failed: http://mirror.ragenetwork.de/manjaro/stable/multilib/x86_64/multilib.files [error 404]
warning: download failed: http://mirror.ragenetwork.de/manjaro/stable/core/x86_64/core.files [error 404]
warning: download failed: http://mirror.ragenetwork.de/manjaro/stable/extra/x86_64/extra.files [error 404]
warning: download failed: http://mirror.ragenetwork.de/manjaro/stable/community/x86_64/community.files [error 404]
warning: download failed: http://mirror.netzspielplatz.de/manjaro/packages/stable/core/x86_64/core.files [error 404]
warning: download failed: http://mirror.netzspielplatz.de/manjaro/packages/stable/multilib/x86_64/multilib.files [error 404]
warning: download failed: http://mirror.netzspielplatz.de/manjaro/packages/stable/extra/x86_64/extra.files [error 404]
warning: download failed: http://mirror.netzspielplatz.de/manjaro/packages/stable/community/x86_64/community.files [error 404]
warning: download failed: http://mirrors.xservers.ro/manjaro/stable/multilib/x86_64/multilib.files [error 404]
warning: download failed: http://mirrors.xservers.ro/manjaro/stable/community/x86_64/community.files [error 404]
warning: download failed: http://mirrors.xservers.ro/manjaro/stable/core/x86_64/core.files [error 404]
warning: download failed: http://mirrors.xservers.ro/manjaro/stable/extra/x86_64/extra.files [error 404]
warning: download failed: http://mirror.lignux.com/manjaro/stable/multilib/x86_64/multilib.files [error 404]
warning: download failed: http://mirror.lignux.com/manjaro/stable/community/x86_64/community.files [error 404]
warning: download failed: http://mirror.lignux.com/manjaro/stable/extra/x86_64/extra.files [error 404]
warning: download failed: http://mirror.lignux.com/manjaro/stable/core/x86_64/core.files [error 404]
warning: download failed: http://mirror.solarvps.com/manjaro/stable/multilib/x86_64/multilib.files [error 404]
warning: download failed: http://mirror.solarvps.com/manjaro/stable/core/x86_64/core.files [error 404]
warning: download failed: http://mirror.solarvps.com/manjaro/stable/community/x86_64/community.files [error 404]
warning: download failed: http://mirror.solarvps.com/manjaro/stable/extra/x86_64/extra.files [error 404]
warning: download failed: http://ftp.lysator.liu.se/pub/manjaro/stable/core/x86_64/core.files [error 404]
warning: download failed: http://ftp.lysator.liu.se/pub/manjaro/stable/multilib/x86_64/multilib.files [error 404]
warning: download failed: http://ftp.lysator.liu.se/pub/manjaro/stable/extra/x86_64/extra.files [error 404]
warning: download failed: http://ftp.lysator.liu.se/pub/manjaro/stable/community/x86_64/community.files [error 404]
warning: download failed: http://manjaro.mirrors.uk2.net/stable/multilib/x86_64/multilib.files [error 404]
warning: download failed: http://manjaro.mirrors.uk2.net/stable/core/x86_64/core.files [error 404]
warning: download failed: http://manjaro.mirrors.uk2.net/stable/extra/x86_64/extra.files [error 404]
warning: download failed: http://manjaro.mirrors.uk2.net/stable/community/x86_64/community.files [error 404]
warning: download failed: http://www.mirrorservice.org/sites/repo.manjaro.org/repos/stable/multilib/x86_64/multilib.files [error 404]
warning: download failed: http://www.mirrorservice.org/sites/repo.manjaro.org/repos/stable/core/x86_64/core.files [error 404]
warning: download failed: http://www.mirrorservice.org/sites/repo.manjaro.org/repos/stable/extra/x86_64/extra.files [error 404]
warning: download failed: http://www.mirrorservice.org/sites/repo.manjaro.org/repos/stable/community/x86_64/community.files [error 404]
warning: download failed: http://ftp.belnet.be/manjaro/stable/multilib/x86_64/multilib.files [error 404]
warning: download failed: http://ftp.belnet.be/manjaro/stable/core/x86_64/core.files [error 404]
warning: download failed: http://ftp.belnet.be/manjaro/stable/extra/x86_64/extra.files [error 404]
warning: download failed: http://ftp.belnet.be/manjaro/stable/community/x86_64/community.files [error 404]
warning: download failed: http://manjaro.mirror.garr.it/mirrors/manjaro/stable/multilib/x86_64/multilib.files [error 404]
warning: download failed: http://manjaro.mirror.garr.it/mirrors/manjaro/stable/core/x86_64/core.files [error 404]
warning: download failed: http://manjaro.mirror.garr.it/mirrors/manjaro/stable/community/x86_64/community.files [error 404]
warning: download failed: http://manjaro.mirror.garr.it/mirrors/manjaro/stable/extra/x86_64/extra.files [error 404]
warning: download failed: http://manjaro.uberglobalmirror.com/stable/multilib/x86_64/multilib.files [error 404]
warning: download failed: http://manjaro.uberglobalmirror.com/stable/core/x86_64/core.files [error 404]
warning: download failed: http://manjaro.uberglobalmirror.com/stable/community/x86_64/community.files [error 404]
warning: download failed: http://manjaro.uberglobalmirror.com/stable/extra/x86_64/extra.files [error 404]
warning: download failed: http://mirrors.tuna.tsinghua.edu.cn/manjaro/stable/core/x86_64/core.files [error 404]
warning: download failed: http://mirrors.tuna.tsinghua.edu.cn/manjaro/stable/multilib/x86_64/multilib.files [error 404]
warning: download failed: http://mirrors.tuna.tsinghua.edu.cn/manjaro/stable/community/x86_64/community.files [error 404]
warning: download failed: http://mirrors.tuna.tsinghua.edu.cn/manjaro/stable/extra/x86_64/extra.files [error 404]
warning: download failed: http://mirror.zetup.net/manjaro/stable/core/x86_64/core.files [error 404]
warning: download failed: http://mirror.zetup.net/manjaro/stable/multilib/x86_64/multilib.files [error 404]
warning: download failed: http://mirror.zetup.net/manjaro/stable/community/x86_64/community.files [error 404]
warning: download failed: http://mirror.zetup.net/manjaro/stable/extra/x86_64/extra.files [error 404]
warning: download failed: http://ftp.riken.jp/Linux/manjaro/stable/extra/x86_64/extra.files [error 404]
warning: download failed: http://ftp.riken.jp/Linux/manjaro/stable/multilib/x86_64/multilib.files [error 404]
warning: download failed: http://ftp.riken.jp/Linux/manjaro/stable/core/x86_64/core.files [error 404]
warning: download failed: http://ftp.riken.jp/Linux/manjaro/stable/community/x86_64/community.files [error 404]
warning: download failed: http://manjaro.mirrors.linux.ro/repos/stable/extra/x86_64/extra.files [error 404]
warning: download failed: http://manjaro.mirrors.linux.ro/repos/stable/multilib/x86_64/multilib.files [error 404]
warning: download failed: http://manjaro.mirrors.linux.ro/repos/stable/core/x86_64/core.files [error 404]
warning: download failed: http://manjaro.mirrors.linux.ro/repos/stable/community/x86_64/community.files [error 404]
warning: download failed: https://manjaro.cu.be/stable/extra/x86_64/extra.files [error 404]
warning: download failed: https://manjaro.cu.be/stable/multilib/x86_64/multilib.files [error 404]
warning: download failed: https://manjaro.cu.be/stable/core/x86_64/core.files [error 404]
warning: download failed: https://manjaro.cu.be/stable/community/x86_64/community.files [error 404]
  download complete: core                 [   596,0   B   483B/s  3 remaining]
error: failed to create archive reader for core: Multibyte ou caracter largo inválido
  download complete: extra                [   596,0   B   473B/s  2 remaining]
error: failed to create archive reader for extra: Multibyte ou caracter largo inválido
  download complete: multilib             [   596,0   B   464B/s  1 remaining]
error: failed to create archive reader for multilib: Multibyte ou caracter largo inválido
  download complete: community            [   596,0   B   484B/s  0 remaining]
:: download complete in 20,58s            <     2,3 KiB   115B/s  4 files    >
:: waiting for 1 process to finish repacking repos...
error: failed to create archive reader for community: Multibyte ou caracter largo inválido
Synchronization failed. Exiting...

**Comment by helixarch** [comment]
Manjaro doesn't support yet pkgfile, so debtap cannot run on Manjaro or Manjaro-based distros

**Comment by talesam** [comment]
I have installed the pkg file:

[talesam@neit ~]$ pacman -Q |grep pkgfile
pkgfile-git 15.7.g7ace342-1

**Comment by helixarch** [comment]
That's not enough. See

**Comment by helixarch** [comment]
That's not enough. See this thread:

https://forum.manjaro.org/index.php?topic=9268.0
