### ISSUE TITLE
can't update anymore

### ISSUE THREAD

**Issue by digitalirony** [helixarch/debtap#18]
[root@deepthought ~]#  curl -C - -f http://archive.ubuntu.com/ubuntu/dists/yakkety/Contents-amd64.gz
curl: (22) The requested URL returned error: 404 Not Found

http://archive.ubuntu.com/ubuntu/dists/yakkety/ exists, but there is not Contents-*.gz file at all.

**Comment by helixarch** [comment]
Update: debtap uses now by default stable instead of development version, in this date is xenial
