### ISSUE TITLE
Help output shows duplicate options

### ISSUE THREAD

**Issue by jamesbvaughan** [helixarch/debtap#19]
When I run `$ debtap -h` I get this:

```
Syntax: debtap [option] package_filename

Options:

      -h  --h  -help    --help        Prints this help message
      -u  --u  -update  --update      Update debtap database
      -q  --q  -quiet   --quiet       Bypass all questions, except for editing metadata file(s)
      -Q  --Q  -Quiet   --Quiet       Bypass all questions (not recommended)
```

**Comment by helixarch** [comment]
There is nothing duplicate on this

**Comment by jamesbvaughan** [comment]
Oops, I didn't notice that it included "-h" and "--h", etc. My bad.

**Comment by jamesbvaughan** [comment]
@helixarch Just curious, why did you include all permutations of "-", "--", and the options rather than the usual "-" for short options and "--" for their full names?

**Comment by helixarch** [comment]
Makes it easier for someone to remember... He/She doesn't have to remember if he/she should use one or two -, so I took all combinations.
