### ISSUE TITLE
debtap exits with 404 error

### ISSUE THREAD

**Issue by drrobotnic** [helixarch/debtap#20]
I tried using debtap to convert openarena to arm arch linux as the aur package does not support armv7h architecture. When I try to convert, I get 
`Error: You must run at least once "debtap -u" with root privileges (preferably recently), before running this script`
So I ran the debtap -u command and it exits with the said 404 error
`==> Synchronizing pkgfile database...
:: Updating 5 repos...
  core is up to date
  aur is up to date
  alarm is up to date
  community is up to date
  extra is up to date
==> Synchronizing debtap database...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found

gzip: /var/cache/debtap/debian-packages-files.gz: unexpected end of file
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found

gzip: /var/cache/debtap/ubuntu-packages-files.gz: unexpected end of file
Synchronization failed. Exiting...`

This is the output of the 'curl -s http://packages.ubuntu.com | grep option | gawk -F '=' '{print $2}' | gawk '{print $1}' | grep -v option | tac | sed -n 2'{p;q;}' | sed s'/("|-updated|-backports)//g''

"yakkety"

Any help would be appreciated

**Comment by helixarch** [comment]
That's because debtap doesn't support ARM architecture and debtaparm is incomplete at the moment

**Comment by drrobotnic** [comment]
OK thanks alot then will close issue

**Comment by drrobotnic** [comment]
close
