### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by Spiilgriim** [helixarch/debtap#21]
Hi there I'm quite new on arch and I needed debtap to use a very specific emacs tool called caml tuareg to use emacs and camllight. Each time I try to update it I get a lot of 404 (and some 502) errors, the update finally ends with the message: "All steps fully completed".Then when I try to use debtap on my deb file, I'm asked to update it again. How can I solve this?

Thanks in advance for the help.

**Comment by helixarch** [comment]
What is your operating system?

**Comment by Spiilgriim** [comment]
Sorry I read only after the topic you already answered, I also use manjaro.
