### ISSUE TITLE
 /usr/bin/bash: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by josep112** [helixarch/debtap#23]
Hello I installed the dependencies as per request but I received the following error when executing:
./debtap -u verbio-asr-pt-br_9.00_amd64.deb 
bash: ./debtap: /usr/bin/bash: bad interpreter: No such file or directory

**Comment by helixarch** [comment]
What is your distro?

**Comment by helixarch** [comment]
No response, closing
