### ISSUE TITLE
How do I specify the Debian source repository?

### ISSUE THREAD

**Issue by qwIvan** [helixarch/debtap#24]

**Comment by helixarch** [comment]
Why would you do that?

**Comment by qwIvan** [comment]
I want to convert deepin package to arch package.

**Comment by helixarch** [comment]
Is that a deb package? If so, just run debtap on it.

**Comment by qwIvan** [comment]
But there are serveral package dosen't in debian source

**Comment by qwIvan** [comment]
Include dependency of these package.

**Comment by helixarch** [comment]
That's not a problem, run "debtap -u" as root or with sudo, then run "debtap the_name_of_the_package.deb"
