### ISSUE TITLE
Multiple file processing in one command

### ISSUE THREAD

**Issue by piepie62** [helixarch/debtap#3]
I'm not sure exactly where to put this, but I would really like it if you added the ability to convert multiple packages in one command. I don't mean do them all at once, just have it so that you don't need to enter 'debtap [option] filename' each time. This would be greatly appreciated.

**Comment by helixarch** [comment]
You can do this with a simple for loop:

for i in *.deb; do debtap [option] $i; done

**Comment by piepie62** [comment]
Yes, but I mean so that one could start it online, then have it continue without needing the internet. It only would need to download the aur packages file once, as it wouldn't need to update it.

**Comment by helixarch** [comment]
The scripts uses internet to download information from it, this happens for every single package you convert so when the first package is converted,  for the second one access to internet is needed too and so on.

**Comment by piepie62** [comment]
But that is the point of what I am saying, it downloads the aurpackages file, but I don't think you need to update it every minute. The script could just store it somewhere and access it for the packages listed. Then it would update it the next time.

**Comment by helixarch** [comment]
Even if the specific file (called aur-packages) is stored somewhere and recalled every time it is needed, access to internet is STILL needed for the next package you want to convert, it is required for the first two methods of packages-names-translator function (inside the script) that need access to the Debian & Ubuntu webpages to get a list of files for every package which is part of dependencies. These dependencies are not the same for every package-to-be-converted and this is the reason the script needs to reaccess internet for every package it converts, if you get my point. If you have any suggestion about how it is possible to have a database with all official .deb packages list of files (in a similar way pkgfile -u does for Arch Linux packages), I would be glad to hear it.

**Comment by piepie62** [comment]
You could download the "http://packages.ubuntu.com/RELEASE-NAME/allpackages?format=txt.gz" file, then "zcat > packages.txt" it (maybe concatenate a couple of them) and use that. Maybe every couple of days remind people to update it with debtap -u or something like that?

**Comment by helixarch** [comment]
The address gives me error, check again please

**Comment by helixarch** [comment]
My bad, I had to replace RELEASE-NAME with an actual release name, like utopic. But such a link gives a list of all ubuntu packages for this release. This is not what I meant. What I need is a list of all packages PLUS a list of containing files for EACH ONE of tthese packages. That's what the first two methods need to work.

I did my own research. The necessary files (used by apt-file, equivalent of pkgfile for .deb distros) are these:

http://gb.archive.ubuntu.com/ubuntu/dists/RELEASE-NAME/Contents-i386.gz
http://gb.archive.ubuntu.com/ubuntu/dists/RELEASE-NAME/Contents-amd64.gz
http://ftp.pl.debian.org/debian/dists/sid/Contents-i386.gz
http://ftp.pl.debian.org/debian/dists/sid/Contents-amd64.gz

First two are for Ubuntu, last two are for Debian. So here is the first problem: each one of these is about 30 MB of size, that means 4 x 30 MB = 120 MB. Isn't this size considered enormous for a packages files database? The size for pkgfile database is much, much smaller than 30 MB.

**Comment by piepie62** [comment]
I suppose it could be considered gigantic; what about the thing that apt-file uses? Or is that the same?

**Comment by helixarch** [comment]
Check new version 2.0 and tell me your opinion about it. It supports offline convertion, as long as you run "debtap -u" first.

**Comment by piepie62** [comment]
I needed to create the /var/cache/debtap directory; I suggest you add that to the install file.

**Comment by helixarch** [comment]
I did that already, check the AUR package

**Comment by piepie62** [comment]
Well, when I just installed it from the aur and did debtap -u, it said that the directory was missing.

**Comment by piepie62** [comment]
You need to add it to the post-upgrade method, the people who already have it installed need that to happen.

**Comment by helixarch** [comment]
Ok, but do you know how it will create the /var/cache/debtap directory? The command I use in debtap.install strangely doesn't work.

**Comment by piepie62** [comment]
Well, you just need to put something like "if [ ! -a /var/cache/debtap ]; then mkdir /var/cache/debtap; fi" into the post_upgrade method. I accidentally said post-upgrade before, sorry.

**Comment by helixarch** [comment]
That if doesn't work either

**Comment by helixarch** [comment]
Much be OK now, check the latest release 2.0-3

**Comment by piepie62** [comment]
Yep, that works. Thank you for your work on this!

**Comment by helixarch** [comment]
You are welcome... Keep in mind that debtap cache with the files uncompressed is about 800 MB. And btw there is a minor update 2.0.2, which I suggest you upgrade to.
