### ISSUE TITLE
does not wirk with control.tar.xz

### ISSUE THREAD

**Issue by jjgalvez** [helixarch/debtap#36]
looks like the new deb packages contain control.tart.xz rather than control.tart.gz. Please update you package to handle them. I replaced the line  ar p "$package_with_full_path" control.tar.gz | tar xz with
control_tar_check=`ar t "$package_with_full_path" | grep control`
if [[ $control_tar_check == control.tar.gz ]]; then
	ar p "$package_with_full_path" control.tar.gz | tar xz
elif [[ $control_tar_check == control.tar.xz ]]; then
	ar p "$package_with_full_path" control.tar.xz | tar xJ
fi

which seems to be inline with your code and seems to work.

Thanks and  BTW great script

**Comment by helixarch** [comment]
Thank you, fixed in 3.2
