### ISSUE TITLE
zx compression preset

### ISSUE THREAD

**Issue by makall** [helixarch/debtap#39]
Hi, first of all thanks for your work, it helped me a lot.

I was trying to convert the file above in my raspberry 3 b+ and I had some memories issue during the "Creating final package..." step. Then I removed the "-9" (compression preset) from xz command line and everything went fine as expected.

So I was wondering if you could change the default preset to xz's default or make it configurable. Either way, it would help users with the same issue.

Thanks.

https://github.com/MediaBrowser/Emby.Releases/releases/download/4.1.0.14/emby-server-deb_4.1.0.14_armhf.deb

**Comment by lllars** [comment]
Thanks for this.  I ran into the same issue trying to install phantomjs:

```
==> Creating final package...
xz: phantomjs-2.1.1-1-armv7h.pkg.tar: Cannot allocate memory
mv: cannot stat '*.xz': No such file or directory
==> Package successfully created!
```

Removing the -9 option fixed it

**Comment by helixarch** [comment]
Switched to zstd compression in 3.3
