### ISSUE TITLE
arm support

### ISSUE THREAD

**Issue by frudas24** [helixarch/debtap#4]
any way to add arm support?
thankx

**Comment by helixarch** [comment]
I don't own any machine capable of running Arch Linux ARM, neither I have used this distro before :/

**Comment by frudas24** [comment]
What if i give you one? :)

**Comment by helixarch** [comment]
How are you going to do that?

**Comment by frudas24** [comment]
Amazon + delivery anywhere in the world :)

**Comment by helixarch** [comment]
Can we continue this discussion in my personal e-mail stargr@gmail.com please?

**Comment by frudas24** [comment]
Of course :)

**Comment by dschaper** [comment]
http://ports.ubuntu.com/ubuntu-ports/dists/wily/Contents-armhf.gz
and 
http://ftp.debian.org/debian/dists/sid/Contents-armhf.gz
are the locations for the armv71 (Raspberry Pi 2)

**Comment by helixarch** [comment]
Closing this due to lack of necessary equipement (ARM hardware)
