### ISSUE TITLE
Brother printer drivers- Incorrect translation of some file locations

### ISSUE THREAD

**Issue by incansvl** [helixarch/debtap#44]
OS: Manjaro 5.3.12
Debtap: 3.2.2

**Background**
Just installed Manjaro/Arch. I have a Brother MFC 7820N network printer. As a specific driver for this printer doesn't seem to exist in the repos or AUR, the aim was to use Debtap to convert the .deb files supplied by Brother.

**Target Files**
1. [brmfc7820nlpr-2.0.1-1.i386.deb](https://support.brother.com/g/b/link.aspx?os=128&type3=559)
1. [cupswrapperMFC7820N-2.0.1-2.i386.deb](https://download.brother.com/welcome/dlf006268/cupswrapperMFC7820N-2.0.1-2.i386.deb)

**To Reproduce**
1. Download and save the .deb files to a working directory
1. cd to the directory. Run-
- debtap -s brmfc7820nlpr-2.0.1-1.i386.deb
- debtap -s cupswrapperMFC7820N-2.0.1-2.i386.deb
1. Attempt to install-
- sudo pacman -U brmfc7820nlpr-2.0.1-1-x86_64.pkg.tar.xz
- sudo pacman -U cupswrappermfc7820n-2.0.1-1-x86_64.pkg.tar.xz

**Symptoms**
Installation of both packages fails with a number of errors, including several "file not found" errors for files in `/usr/local/Brother`. By inspection I could see the packages created by debtap had what looked like the right files, but had installed some of them in `/usr/Brother`.

I manually moved/coped the contents of `/usr/Brother` over to `/usr/local/Brother` and deleted the now empty `/usr/Brother `directory. After this I was able to go into CUPS admin and by updating the printer to find it's network location, I was able to get the printer working.

It's possible debtap has simply mis-translated the location of these files. However from experience with the Brother drivers on windows I know the installers can be quite clunky and seem to run pre or post- install scripts. I wonder if there is a script in here somewhere that is expected to move the driver files into a platform-dependent location?

Note: I can upload the converted packages if that would be useful, but I don't want to add unecessarily large attachments to the bug report.

**Comment by helixarch** [comment]
Fixed in 3.3
