### ISSUE TITLE
errors from the .INSTALL

### ISSUE THREAD

**Issue by jdtsillas** [helixarch/debtap#47]
These show up when install or removing the generated package using packman:

/tmp/alpm_XNlaz5/.INSTALL: line 534: unexpected EOF while looking for matching ``'
/tmp/alpm_XNlaz5/.INSTALL: line 567: syntax error: unexpected end of file

I am using the debtap binary installed from AUR using yay:

[viasat@Manjaro ~]$ debtap -v
3.2.2

**Comment by helixarch** [comment]
Edit manually .INSTALL during convertion process, debtap will not fix it for you
