### ISSUE TITLE
Peculiar dependency

### ISSUE THREAD

**Issue by Nemo-Nowane** [helixarch/debtap#49]
As I transformed  [Atom nightly](https://atom.io/nightly) debian package into alpm in Manjaro, it included dependency like [tuxedo-control-center](https://github.com/tuxedocomputers/tuxedo-control-center) and [Metasploit Framework](https://github.com/rapid7/metasploit-framework). You may look in this issue
Prerequisites to reproduce: 

- A Manjaro Linux Lysia installation
- Metasploit and Tuxedo control center previously installed (I don't use a Tuxedo, it came with XFCE)
- `atom-amd64.deb` from above link.
- `debtap` script

Way to reproduce:
- `debtap atom-amd64.deb`
- See `.PKGBUILD`

**Comment by helixarch** [comment]
Remove unnecessary dependencies from .PKGINFO manually when you create your package
