### ISSUE TITLE
debtap got the names of dependencies connected together

### ISSUE THREAD

**Issue by SamLukeYes** [helixarch/debtap#51]
When I tried to generate a PKGBUILD for vst-video.deb ([https://github.com/xymov/vst-video/releases/download/V2.55/vst-video.deb](url)), I got a dependency like this:

`libqt5xml5libqt5concurrent5libqt5multimedia5libqt5multimediawidgets5libqt5core5alibqt5gui5libqt5widgets5libqt5network5
`

I checked the control file inside the package, the dependencies are written like this:

`Depends:libqt5xml5,libqt5concurrent5,libqt5multimedia5,libqt5multimediawidgets5,libqt5core5a,libqt5gui5,libqt5widgets5,libqt5network5`

It seems that the missing spaces after commas caused debtap failing to read the dependencies. Is this a bug in debtap?

**Comment by helixarch** [comment]
Fixed in 3.3.1
