### ISSUE TITLE
Why do we need root permission to convert a deb package to arch package?

### ISSUE THREAD

**Issue by trusktr** [helixarch/debtap#52]
Is it so that it will download all the dependencies from the debian/ubuntu repos?

**Comment by trusktr** [comment]
Is there a way to skip this root step if we have a package that we don't need dependencies for?

**Comment by helixarch** [comment]
You DON'T need root permissions to convert a deb package, you only need root permissions to update debtap database, because it is stored in /car/cache/debtap which needs root permissions to write to. And even this step is only needed once to be run.
