### ISSUE TITLE
Script Broken: PKGBUILD Cannot Be Created if .deb package doesn't contain any usr/bin files

### ISSUE THREAD

**Issue by gardotd426** [helixarch/debtap#54]
You've already closed a similar issue because you didn't read what the person was saying and told them their installation was broken. 

If you simply try to CONVERT a .deb package that doesn't contain any `/usr/bin` files (let's say for this example it only contains files in `/usr/share` and `/etc`), the conversion will work fine. 

But if you try to create a PKGBUILD, it will fail with this error:
```
==> Generating PKGBUILD file...
ls: cannot access 'usr/bin': No such file or directory
Error: Cannot create PKGBUILD directory, permission denied. Removing leftover files and exiting...
```
It's trying to `ls` in the `usr/bin` directory IN THE PACKAGE, but there isn't one, because the original .deb didn't have anything in `usr/bin`. Again, ***this is not a broken installation***. At all. Your script is broken. 

Again, it will ***convert*** packages perfectly fine, but it ***cannot*** create a PKGBUILD if the package doesn't contain anything in usr/bin. I'll give you two examples so you don't try to write this off as someone having a "broken installation" and then close the issue:

I have two .deb packages: `i3-snapshot_1.0-1ubuntu1~ppa1_amd64.deb`, and `vulkan-amdgpu-pro_20.10-1048554_amd64.deb`. Let's look at their containing files:

```
dpkg-deb -c i3-snapshot_1.0-1ubuntu1~ppa1_amd64.deb

drwxr-xr-x root/root         0 2019-12-14 22:00 ./
drwxr-xr-x root/root         0 2019-12-14 22:00 ./usr/
drwxr-xr-x root/root         0 2019-12-14 22:00 ./usr/bin/
-rwxr-xr-x root/root    129272 2019-12-14 22:00 ./usr/bin/i3-snapshot
drwxr-xr-x root/root         0 2019-12-14 22:00 ./usr/share/
drwxr-xr-x root/root         0 2019-12-14 22:00 ./usr/share/doc/
drwxr-xr-x root/root         0 2019-12-14 22:00 ./usr/share/doc/i3-snapshot/
-rw-r--r-- root/root       248 2019-12-14 22:00 ./usr/share/doc/i3-snapshot/changelog.Debian.gz
-rw-r--r-- root/root      4588 2019-12-14 22:00 ./usr/share/doc/i3-snapshot/copyright
```
Notice, the i3-snapshot has files in usr/bin. Now, let's look at the other one:

```
drwxr-xr-x root/root         0 2020-04-08 23:50 ./
drwxr-xr-x root/root         0 2020-04-08 23:50 ./etc/
drwxr-xr-x root/root         0 2020-04-08 23:50 ./etc/vulkan/
drwxr-xr-x root/root         0 2020-04-08 23:50 ./etc/vulkan/icd.d/
drwxr-xr-x root/root         0 2020-04-08 23:50 ./opt/
drwxr-xr-x root/root         0 2020-04-08 23:50 ./opt/amdgpu-pro/
drwxr-xr-x root/root         0 2020-04-08 23:50 ./opt/amdgpu-pro/etc/
drwxr-xr-x root/root         0 2020-04-08 23:50 ./opt/amdgpu-pro/etc/vulkan/
drwxr-xr-x root/root         0 2020-04-08 23:50 ./opt/amdgpu-pro/etc/vulkan/icd.d/
-rw-r--r-- root/root       173 2020-04-08 23:50 ./opt/amdgpu-pro/etc/vulkan/icd.d/amd_icd64.json
drwxr-xr-x root/root         0 2020-04-08 23:50 ./opt/amdgpu-pro/lib/
drwxr-xr-x root/root         0 2020-04-08 23:50 ./opt/amdgpu-pro/lib/x86_64-linux-gnu/
-rw-r--r-- root/root  42276064 2020-04-08 23:50 ./opt/amdgpu-pro/lib/x86_64-linux-gnu/amdvlk64.so
drwxr-xr-x root/root         0 2020-04-08 23:50 ./usr/
drwxr-xr-x root/root         0 2020-04-08 23:50 ./usr/share/
drwxr-xr-x root/root         0 2020-04-08 23:50 ./usr/share/doc/
drwxr-xr-x root/root         0 2020-04-08 23:50 ./usr/share/doc/vulkan-amdgpu-pro/
-rw-r--r-- root/root       243 2020-04-08 23:50 ./usr/share/doc/vulkan-amdgpu-pro/changelog.Debian.gz
-rw-r--r-- root/root      9551 2020-04-08 23:50 ./usr/share/doc/vulkan-amdgpu-pro/copyright
```

Notice, this .deb has NO files in usr/bin, therefore the package won't have a usr/bin

So, when you run `debtap -P i3-snapshot_1.0-1ubuntu1~ppa1_amd64.deb`, it runs perfectly, and creates a PKGBUILD, but when you run `debtap -P vulkan-amdgpu-pro_20.10-1048554_amd64.deb`, it fails with:

```
==> Generating PKGBUILD file...
ls: cannot access 'usr/bin': No such file or directory
Error: Cannot create PKGBUILD directory, permission denied. Removing leftover files and exiting...
```

Because somewhere in your script, when it comes time to create a PKGBUILD, You're trying to ls a directory in the package that ***does not exist***. 

The script is gigantic, I'm trying to parse through it and find the offending location, but it'll take me a while. When I do, I'll post it, though I'm sure you know exactly where you call for this. 

I hope you don't just close this issue like you did the other one, because that person was definitely correct. If the package being created DOES NOT contain any ./usr/bin/ files, it WILL fail trying to create a PKGBUILD.

**Comment by gardotd426** [comment]
This is the offending line, it seems:

```
if [[ $(grep -q '^pkgname = lib32-' .PKGINFO; echo $?) != 0 ]] && [[ $(grep '^pkgname =' .PKGINFO | grep -q -- '-multilib$'; echo $?) != 0 ]] && [[ $(ls -A usr/bin) ]]; then
```
I've been trying to edit the script to get it to work (but it seems I've found another bug, not sure yet), so I don't know the exact line, but it's between lines 3190 and 3200. Toward the beginning of the `Generating PKGBUILD file...` section. 

It seems like you're using ls `usr/bin` to determine whether it's a binary package, but for some reason that's causing the script to fail when there is no usr/bin. 

Yeah, I just removed the offending line, and the PKGBUILD succeeds with no errors. Unfortunately because of the script being almost 4000 lines and me not knowing what all the variables are, and just the complexity of it, I don't know what other issues that might cause, but it does create a PKGBUILD (though not a functional one, but that's got nothing to do with the removed line)

**Comment by helixarch** [comment]
Please uncomment line #3191 (for some strange reason I had "else" commented) and tell me if it's working correctly.

**Comment by gardotd426** [comment]
Lord, I saw that line, but it was after I'd started editing to try and find a workaround and it was literally right under my edits, and I thought *I'd* commented it out, lol. 

Anyways, that "worked," but only partially, it seems. 

I still get the error message:
```
==> Generating PKGBUILD file...
ls: cannot access 'usr/bin': No such file or directory
```
But it does still finish. But I was under the impression that any error is supposed to lead to failure in your script (which is what all the `if [[ $(grep -q "^a bunch of stuff; echo $?) != 0 ]]; fail message` (obviously that's simplifying but I noticed a lot of that kind of stuff). 

And then, when I check the resulting PKGBUILD, it's not remotely usable. I don't mean the "ADD URL HERE" stuff, that's to be expected, I mean the actual packaging part. Here's what I get for the vulkan-amdgpu-pro package:
```
package(){

        # Extract package data
        tar xf data.tar.xz -C "${pkgdir}"

        install -D -m644 "/usr/share/doc/vulkan-amdgpu-pro/copyright" "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"

}
```
It doesn't extract the deb, it doesn't move any files except the copyright for some reason, there's no way this can be intended behavior, is it? If so, that's fine, you can close this issue and we can maybe open another one to try and get some closer-to-functioning PKGBUILDS, but I feel like this is in error. 

But yeah, that did seem to stop it from just failing completely and not even providing a PKGBUILD at all.

**Comment by helixarch** [comment]
Ok, clone my latest upload of debtap, try it and tell me. Should be OK now!

**Comment by gardotd426** [comment]
Awesome. It still gives a PKGBUILD that couldn't function at all though, (it would literally have to be completely re-written, only the Maintainer part and a few of the top lines would be usable), should that be a separate issue?

**Comment by helixarch** [comment]
Yes, open a new issue

**Comment by arichiardi** [comment]
I have run into this one as well. Thanks for attempting a fix.
