### ISSUE TITLE
 libstdc++6 (>= 5.2) converts to depend = aarch64-linux-gnu-gcc>=5.2 on x86_64

### ISSUE THREAD

**Issue by Jau-nee** [helixarch/debtap#58]
I have got a license for the commercial Varicad program.  Since I have just switched from Xubuntu to Manjaro I used the debtab script to successfully convert the .deb Package. 

Varicad...deb lists in its control part a libstdc++6 dependency. This leads to depend = aarch64-linux-gnu-gcc>=5.2 in .PKGINFO. An ARM64 lib for a x86_64 System?? Maybe the Tables are wrong at this point? I have changed this by hand to libstdc++5. This works. But I am not sure if that is needed because the standard c++ lib should be part of gcc-lib? Now my system has this dependency ... preventing me to deinstall libstdc++5.

There is no notice in the readme about the Packager and the License questions yet. Nothing but enter worked. And any other key than 1,2 or 4 skips the editor on my system. The Varicad program installs to /opt/VariCAD/bin/varicad and installs a link at /usr/bin to that. So pamac notes wrong that varicad was not installed. But that are very mini problems.

@ Helix: But the very first thing now:   THANK YOU FOR THE SCRIPT!
This is a way to get even commercial software running.

**Comment by helixarch** [comment]
Thank you for your kind words... Fixed in 3.4, closing...
