### ISSUE TITLE
Can't download latest virtual packages list

### ISSUE THREAD

**Issue by cnjawi** [helixarch/debtap#67]
when i use debtap -u, it always fails at the step "Downloading latest virtual packages list".
I wonder how to solve this issue.
![Screenshot_20210425_050701](https://user-images.githubusercontent.com/58169689/115972946-26ca7280-a584-11eb-848f-c44e9fe9cb80.png)

**Comment by helixarch** [comment]
Do you use zsh?

**Comment by helixarch** [comment]
Yes, use bash instead...
