### ISSUE TITLE
Error on building Epson Scanner package (iScan.deb) on Manjaro

### ISSUE THREAD

**Issue by SnorreQWERTY** [helixarch/debtap#70]
Hello,

I try to convert the Epson scanner package (iScan) 
1. Link (overview): http://download.ebz.epson.net/dsc/search/01/search/searchModule   ... search for "4490" and then any of these two scanners.
2. Link (Download): http://download.ebz.epson.net/dsc/du/02/DriverDownloadInfo.do?LG2=DE&CN2=&DSCMI=97935&DSCCHK=b0b500b7d5437411c661f8a1693ffb35f87a93af

I decompressed the "iscan-gt-V200-2.30.4.x64.deb.tar.gz" file into a folder and put the debtab.sh into every of the three folders with an .deb file.
a) core
b) data
c) plugins

... and try to convert the deb-files

I got these messages:
= = = = = = = = = = 
[user@computer data]$ sudo ./debtab.sh iscan-data_1.39.2-1_all.deb 
==> Extracting package data...
==> Fixing possible directories structure differencies...
==> Generating .PKGINFO file...

:: Enter Packager name:
iscan_2.30

:: Enter package license (you can enter multiple licenses comma separated):
no

*** Creation of .PKGINFO file in progress. It may take a few minutes, please wait...

Warning: These conflicts (conflict =   fields) could not be translated into Arch Linux packages names:
iscan

==> Checking and generating .INSTALL file (if necessary)...

:: If you want to edit .PKGINFO and .INSTALL files (in this order), press (1) For vi (2) For nano (3) For default editor (4) For a custom editor or any other key to continue: 2

==> Generating .MTREE file...

==> Creating final package...
./debtab.sh: Zeile 3165: fakeroot: Kommando nicht gefunden.
mv: der Aufruf von stat für '*.zst' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
==> Package successfully created!
==> Removing leftover files...
= = = = = = = = = = 

- The error is around fakeroot and ... what the hell is zst?
- Manjaro is one week old and almost fresh.
- I have read that it's possible to find devtab in AUR, but I'm not familiar with AUR, therefore I used the file from this page and made it executable.

Any further information needed?
Does anybody know whats to do?

**_AND: Is there no possibility to convert ALL three packages in one step?_** 
- Do I have to convert all packages in there own folder in a single step?
- and the final installation will be done in three steps?

thanks in advance
Snorre

**Comment by helixarch** [comment]
fakeroot is one of debtap’s dependencies and it should be installed before running the program...

There is no way to run debtap for multiple packages at the moment, but you can try running it in a loop like this:

ls -1 *.deb  | while read  line; do debtap ”$line"; done

**Comment by SnorreQWERTY** [comment]
Hello,

partial "success" after installing fakeroot...

I think, that not much people know that fakeroot is a necessary program which has to be installed. Please insert an message into the script if fakeroot has to be installed. ... AND/OR start installation of fakeroot and give a hint to save all open files and prevent the restart of the system. 

Then I tried to convert the single .deb-files. I get these messages of dependencies. All files are stored in different folders. I can try to move them into a single folder. I dont't know if I have to start the initial epson install.sh. Therefore the files should be in the original folder, but I guess this will turn out to be nonsense.


Error in file 1
= = = = = = = = 
*** Creation of .PKGINFO file in progress. It may take a few minutes, please wait...

Warning: These dependencies (depend =   fields) could not be translated into Arch Linux packages names:
iscan-data
Warning: These conflicts (conflict =   fields) could not be translated into Arch Linux packages names:
iscan-network-nt, iscan-plugin-gt-7200, iscan-plugin-gt-7300, iscan-plugin-gt-9400, iscan-plugin-gt-f520, iscan-plugin-gt-f600

==> Checking and generating .INSTALL file (if necessary)...

:: If you want to edit .PKGINFO and .INSTALL files (in this order), press (1) For vi (2) For nano (3) For default editor (4) For a custom editor or any other key to continue: 


= = = = =


Error in file 2
= = = = = = = = 
*** Creation of .PKGINFO file in progress. It may take a few minutes, please wait...

Warning: These conflicts (conflict =   fields) could not be translated into Arch Linux packages names:
iscan

==> Checking and generating .INSTALL file (if necessary)...

:: If you want to edit .PKGINFO and .INSTALL files (in this order), press (1) For vi (2) For nano (3) For default editor (4) For a custom editor or any other key to continue:


= = = = =


Error in file 3
= = = = = = = = 
*** Creation of .PKGINFO file in progress. It may take a few minutes, please wait...

Warning: These dependencies (depend =   fields) could not be translated into Arch Linux packages names:
iscan
Warning: These conflicts (conflict =   fields) could not be translated into Arch Linux packages names:
iscan

==> Checking and generating .INSTALL file (if necessary)...

:: If you want to edit .PKGINFO and .INSTALL files (in this order), press (1) For vi (2) For nano (3) For default editor (4) For a custom editor or any other key to continue


= = = = =


Snorre
