### ISSUE TITLE
vim command not found?

### ISSUE THREAD

**Issue by lunatictaco** [helixarch/debtap#72]
No vim command found for editing .PKGINFO and .INSTALL files?

`:: If you want to edit .PKGINFO and .INSTALL files (in this order), press (1) For vi (2) For nano (3) For default editor (4) For a custom editor or any other key to continue: 1
/usr/bin/debtap: line 3124: vi: command not found
/usr/bin/debtap: line 3124: vi: command not found

==> Generating .MTREE file...

==> Creating final package...
==> Package successfully created!
==> Removing leftover files...`

**Comment by helixarch** [comment]
Press 4, then enter vim and press enter again
