### ISSUE TITLE
debtap: Zeile 2796: »packages-names-translator«: Ist kein gültiger Bezeichner.

### ISSUE THREAD

**Issue by Soviet-Socialist** [helixarch/debtap#74]
I wanted to use debtap to change the package libopenal-dev.deb to an arch package. and after I typed in :: Enter Packager name:
pacman and :: Enter package license (you can enter multiple licenses comma separated):
GPL it gave me that Error. Sorry for it to be in German. I use a German version of Arch.

**Comment by helixarch** [comment]
If you install debtap throught AUR it will work. See this issue:

https://github.com/helixarch/debtap/issues/63
