### ISSUE TITLE
unexpected token

### ISSUE THREAD

**Issue by zine0** [helixarch/debtap#79]
When I press "sudo pacman -U _name_" to install.
"/tmp/alpm_jrS0xw/.INSTALL: line 75: syntax error near unexpected token `}'
/tmp/alpm_jrS0xw/.INSTALL: line 75: `}'" was printed on my screen.
My version is 3.5.1

Thank for your help

**Comment by clickingbuttons** [comment]
Looks like the issue is the empty bash function syntax.

```sh
pre_install() {
	#
}
```

should be:
```sh
pre_install() {:;}
```

**Comment by zine0** [comment]
Thanks for you help.Now is work
